name: Ambrósio

# Skills 
skills:
  - skill: HelloWorld
    inputs:
      - input: Terminal
        output: [ Terminal, Telegram ]
      - input: Telegram
        output: Telegram
  - skill: GoodbyeWorld
    level: 1
    input: Terminal
    output: [ Terminal, Telegram ]

# Inputs
inputs:
  - Terminal